apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kubertest-node
  name: kubertest-node
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        name: kubertest-node
    spec: 
      containers:
      - image: asia.gcr.io/heroic-throne-207504/kubertest/:0.1
        name: kubertest-node
        ports: 
        - containerPort: 8080