apiVersion: v1
kind: Deployment
metadata:
  labels:
    name: kubertest-node
  name: kubertest-node
spec:
  replicas: 2
  template: 
    metadeta:
      labels:
        name: kubertest-node
    spec: 
      containers:
      - image: asia.gcr.io/heroic-throne-207504/kubertest/2ad8158f0521:0.1
        name: kubertest-node
        ports: 
        - containerPort: 8080